# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bittrex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', default=1)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('PairName', models.CharField(max_length=50)),
                ('High', models.FloatField()),
            ],
        ),
    ]
