# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BittrexVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PairName', models.CharField(max_length=20)),
                ('IdOrder', models.BigIntegerField()),
                ('TimeStamp', models.CharField(default=django.utils.timezone.now, max_length=60)),
                ('Quantity', models.FloatField()),
                ('Price', models.FloatField()),
                ('Total', models.FloatField()),
                ('FillType', models.CharField(max_length=25)),
                ('OrderType', models.CharField(max_length=15)),
            ],
        ),
    ]
