# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exchanges', '0004_auto_20171122_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='bittrexohlc',
            name='Aggregated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bittrextick',
            name='Aggregated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bittrexvolume',
            name='Aggregated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bittrexohlc',
            name='TimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 23, 55, 16, 790738), null=True),
        ),
    ]
