# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Exchanges', '0005_auto_20171123_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bittrexohlc',
            name='TimeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bittrextick',
            name='TimeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bittrexvolume',
            name='TimeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
