# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exchanges', '0006_auto_20171124_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bittrexohlc',
            name='Ask',
        ),
        migrations.RemoveField(
            model_name='bittrexohlc',
            name='BaseVolume',
        ),
        migrations.RemoveField(
            model_name='bittrexohlc',
            name='Bid',
        ),
        migrations.RemoveField(
            model_name='bittrexohlc',
            name='BidDivAsk',
        ),
        migrations.RemoveField(
            model_name='bittrexohlc',
            name='OpenBuyOrders',
        ),
        migrations.RemoveField(
            model_name='bittrexohlc',
            name='OpenSellOrders',
        ),
        migrations.RemoveField(
            model_name='bittrexohlc',
            name='Volume',
        ),
    ]
